import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, cwd + '/App']
src     = Glob('App/*.c')

group = DefineGroup('X-CUBE-AI', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
