clean2:
	-$(RM) $(CC_DEPS)$(C++_DEPS)$(C_UPPER_DEPS)$(CXX_DEPS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(CPP_DEPS)
	-$(RM) $(OBJS) *.elf
	-@echo ' '


*.elf: $(wildcard D:/RT-ThreadStudio/Projects/2021_Summer_School/Project4-Person_detection_RT-AK-main/art-pi-gc0328c-yolo-s-two-class-temp/board/linker_scripts/STM32H750XBHx/link.lds)
