#ifndef __RT_AI_PERSON_YOLO_MODEL_H
#define __RT_AI_PERSON_YOLO_MODEL_H

#include <person_yolo.h>
#include <person_yolo_data.h>

/* model info ... */

// model name
#define RT_AI_PERSON_YOLO_MODEL_NAME			"person_yolo"
#define RT_AI_PERSON_YOLO_WORK_BUFFER_BYTES		AI_PERSON_YOLO_DATA_ACTIVATIONS_SIZE
#define RT_AI_PERSON_YOLO_DATA_WEIGHTS_SIZE		AI_PERSON_YOLO_DATA_WEIGHTS_SIZE

#define RT_AI_PERSON_YOLO_BUFFER_ALIGNMENT		AI_PERSON_YOLO_ACTIVATIONS_ALIGNMENT

#define RT_AI_PERSON_YOLO_IN_NUM				AI_PERSON_YOLO_IN_NUM
#define RT_AI_PERSON_YOLO_IN_1_SIZE				AI_PERSON_YOLO_IN_1_SIZE
#define RT_AI_PERSON_YOLO_IN_1_SIZE_BYTES		AI_PERSON_YOLO_IN_1_SIZE_BYTES
#define RT_AI_PERSON_YOLO_IN_TOTAL_SIZE_BYTES	(AI_PERSON_YOLO_IN_1_SIZE_BYTES)
#define RT_AI_PERSON_YOLO_IN_SIZE_BYTES			{AI_PERSON_YOLO_IN_1_SIZE_BYTES}


#define RT_AI_PERSON_YOLO_OUT_NUM				AI_PERSON_YOLO_OUT_NUM
#define RT_AI_PERSON_YOLO_OUT_1_SIZE			AI_PERSON_YOLO_OUT_1_SIZE
#define RT_AI_PERSON_YOLO_OUT_1_SIZE_BYTES		AI_PERSON_YOLO_OUT_1_SIZE_BYTES
#define RT_AI_PERSON_YOLO_OUT_TOTAL_SIZE_BYTES	(AI_PERSON_YOLO_OUT_1_SIZE_BYTES)
#define RT_AI_PERSON_YOLO_OUT_SIZE_BYTES		{AI_PERSON_YOLO_OUT_1_SIZE_BYTES}


#define RT_AI_PERSON_YOLO_TOTAL_BUFFER_SIZE		(NULL)		//unused

#endif	//end
